name: Build Docker image and Deploy it
on:
  pull_request:
    branches: [ main ]
    paths:
      - 'src/**'
      
  push:
    branches: [ main ]
    paths:
      - 'src/**'

  workflow_dispatch:

jobs:
  project-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: Set up the Maven dependencies caching
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: Install Maven dependencies
        run: mvn install -Dmaven.test.skip
      - name: Build and package project
        run: mvn -f pom.xml package -Dmaven.test.skip
      - name: Show contents of the target directory
        run: ls -la target
      - name: Upload Maven build artifact
        uses: actions/upload-artifact@v1
        with:
          name: jar
          path: ./target/monkeyapi-0.0.1-SNAPSHOT.jar
      - name: publish to registry
        uses: pennsignals/publish_docker-compose@v0.1.0
        with:
          version: "0.0.1"
          docker_compose: 'docker-compose.yml' # required
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
